=== GaryLsp/Hospital-Nueva-Vida/pacientes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pacientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="paciente" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id_paciente" type="xs:integer"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="edad" type="xs:integer"/>
              <xs:element name="fecha_alta" type="xs:date"/>
              <xs:element name="diagnostico" type="xs:string"/>
              <xs:element name="fecha_cita" type="xs:date"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== GaryLsp/Hospital-Nueva-Vida/pacientes.xml
<?xml version="1.0" encoding="utf-8"?>
<pacientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pacientes.xsd">
  <paciente>
    <id_paciente>1</id_paciente>
    <nombre>Juan Pérez</nombre>
    <edad>45</edad>
    <fecha_alta>2024-09-10</fecha_alta>
    <diagnostico>Hipertensión</diagnostico>
    <fecha_cita>2024-09-20</fecha_cita>
  </paciente>
  <paciente>
    <id_paciente>2</id_paciente>
    <nombre>María Gómez</nombre>
    <edad>30</edad>
    <fecha_alta>2024-08-25</fecha_alta>
    <diagnostico>Diabetes</diagnostico>
    <fecha_cita>2024-09-15</fecha_cita>
  </paciente>
  <paciente>
    <id_paciente>3</id_paciente>
    <nombre>Carlos Rodríguez</nombre>
    <edad>29</edad>
    <fecha_alta>2024-07-19</fecha_alta>
    <diagnostico>Asma</diagnostico>
    <fecha_cita>2024-09-30</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>4</id_paciente>
    <nombre>Ana Martínez</nombre>
    <edad>29</edad>
    <fecha_alta>2024-08-10</fecha_alta>
    <diagnostico>Alergias</diagnostico>
    <fecha_cita>2024-09-25</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>5</id_paciente>
    <nombre>Luis Fernández</nombre>
    <edad>61</edad>
    <fecha_alta>2024-08-01</fecha_alta>
    <diagnostico>Artritis</diagnostico>
    <fecha_cita>2024-09-22</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>6</id_paciente>
    <nombre>Laura Sánchez</nombre>
    <edad>40</edad>
    <fecha_alta>2024-09-05</fecha_alta>
    <diagnostico>Hipotiroidismo</diagnostico>
    <fecha_cita>2024-09-28</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>7</id_paciente>
    <nombre>Pedro Gómez</nombre>
    <edad>35</edad>
    <fecha_alta>2024-08-15</fecha_alta>
    <diagnostico>Gastritis</diagnostico>
    <fecha_cita>2024-09-18</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>8</id_paciente>
    <nombre>Isabel Cruz</nombre>
    <edad>50</edad>
    <fecha_alta>2024-07-25</fecha_alta>
    <diagnostico>Colesterol alto </diagnostico>
    <fecha_cita>2024-09-12</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>9</id_paciente>
    <nombre>Míguel Ángel</nombre>
    <edad>33</edad>
    <fecha_alta>2024-08-20</fecha_alta>
    <diagnostico>Migrañas</diagnostico>
    <fecha_cita>2024-09-05</fecha_cita>
  </paciente>
	<paciente>
    <id_paciente>10</id_paciente>
    <nombre>Elena Morales</nombre>
    <edad>38</edad>
    <fecha_alta>2024-09-01</fecha_alta>
    <diagnostico>Fibromialgia</diagnostico>
    <fecha_cita>2024-09-23</fecha_cita>
  </paciente>
	
</pacientes>
